# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-yaml
            -   id: check-added-large-files
            -   id: detect-private-key
            -   id: name-tests-test
            -   id: check-merge-conflict
    -   repo: local
        hooks:
            -   id: linting
                name: Run lint
                entry: make lint
                language: system
                pass_filenames: false
                types: [go]
    # Run pre-commit install --hook-type commit-msg --hook-type pre-push
    -   repo: https://github.com/commitizen-tools/commitizen
        rev: v3.2.2
        hooks:
            -   id: commitizen
