name: DB Migrations

on:
  issue_comment:
    types: [created]

jobs:
  db-migration-approval-flow:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != null && startsWith(github.event.comment.body, '/migrate')
    name: DB Migration
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Approval check and migration run flow
        # uses: varunnayal-org/db-migration-action@feature-test
        uses: ./tmp/github-action/repo
        with:
          repo-token: ${{ secrets.TOKEN_GITHUB }}
          # debug: ${{ env.DEBUG }} # defaults to false
          # pr-base-branch: 'main'  # defaults to main
          migration-db-url: ${{ secrets.MIGRATION_DB_URL }}
          migration-dir: './migrations/test/d1/ddl' #${{ env.MIGRATION_DIR }} # default to "migrations"
          approval-teams: "dba,data"
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          TOKEN_GITHUB_ORIG: ${{ secrets.GITHUB_TOKEN }}
