name: DB Migration Approvals

on:
  issue_comment:
    types: [created]

jobs:
  db-migration-approval-flow:
    runs-on: ubuntu-latest
    name: DB Migration
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Approval check and migration run flow
        uses: ./tmp/github-action/repo
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: ${{ env.DEBUG }}
          migration-db-url: ${{ secrets.MIGRATION_DB_URL }}
          migration-dir: ${{ env.MIGRATION_DIR }}
          approval-teams: ${{ env.MIGRATION_APPROVAL_GITHUB_TEAMS }}
